### ISSUE TITLE
parser has a nervous breakdown on `package` as identifier in sloppy mode

### ISSUE THREAD

**Issue by othiym23** [jscs-dev/esprima-harmony#3]
As seen in `jscs`, running it against [this somewhat whimsically formatted file](https://github.com/npm/read-package-tree/blob/20da8f80bd6cab9e4311492ac44900cba2438587/rpt.js). It yields the following:

```
AssertionError: Unable to add an error, `line` should be a number greater than 0 but undefined given
    at Object.Errors.add (/usr/local/lib/node_modules/jscs/lib/errors.js:41:9)
    at StringChecker.checkString (/usr/local/lib/node_modules/jscs/lib/string-checker.js:150:24)
    at null.<anonymous> (/usr/local/lib/node_modules/jscs/lib/checker.js:40:25)
    at Array.<anonymous> (/usr/local/lib/node_modules/jscs/node_modules/vow/lib/vow.js:699:39)
    at Immediate.callFns [as _onImmediate] (/usr/local/lib/node_modules/jscs/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:369:17)
```

**Comment by markelog** [comment]
It seems as jscs issue, not an esprima one, is there a reason to suspect esprima?

I just checked this file through jscs from git with `jscs rpt.js -p google`, it seems to work fine. 

If problem persist with latest changes, could you post your config and arguments that you pass to jscs?

**Comment by othiym23** [comment]
I believe this to be a bug in jscs's bundled esprima because when I added debugging to the relevant productions in the grammar, I was getting an arg value of null right before a test that checked if arg.type was null. I was using [this settings file](https://github.com/feross/standard/blob/master/rc/.jscsrc), because I was running Java as part of http://npm.im/standard, but I reproduced / troubleshot the issue using a standalone install of `jscs@latest`.

**Comment by othiym23** [comment]
Specifically, in [this production](https://github.com/jscs-dev/esprima-harmony/blob/master/esprima.js#L2891-L2914), after the call to `parseSpreadOrAssignmentProduction()`, the value of `arg` that gets pushed to `args` is `undefined`.

**Comment by qfox** [comment]
@othiym23 Actual? Can't get your config file ;-(

**Comment by othiym23** [comment]
That's because `standard` has quit using jscs (for performance reasons – using two style checkers was making it pretty slow on large projects). I believe [this](https://github.com/feross/standard/blob/ed3dc217a9dc51e3a9eef398461a1da679265324/rc/.jscsrc) was the `.jscsrc` that was causing problems.
