### ISSUE TITLE
Destructuring get/set keywords causes Syntax error

### ISSUE THREAD

**Issue by qfox** [jscs-dev/esprima-harmony#4]
```
let { set } = foo;
let { get } = bar;
```

Ref https://github.com/jscs-dev/node-jscs/issues/1293

**Comment by qfox** [comment]
Problem is here: https://github.com/jscs-dev/esprima-harmony/blob/master/esprima.js#L2665-L2680

**Comment by markelog** [comment]
What do you propose we do here?

**Comment by qfox** [comment]
@markelog Actually, since @mikesherov going to implement spreads into Esprima 2.x — nothing. But looks like we can fix it if something goes wrong in 2.x.

**Comment by markelog** [comment]
If something would go wrong, then it should be an esprima issue

**Comment by qfox** [comment]
Right :smirk_cat:  Let's focus on Esprima then.
