### ISSUE TITLE
Support Generator Comprehensions

### ISSUE THREAD

**Issue by KylePDavis** [jscs-dev/esprima-harmony#5]
I am using `jscs` and the `esnext` option.

It seems that [Array Comprehensions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Array_comprehensions) parse properly but [Generator Comprehensions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Generator_comprehensions) do not.

It would be great to get initial support for parsing these.

**Comment by hzoo** [comment]
We'll probably support this through `babel-jscs`: https://github.com/jscs-dev/babel-jscs which I'l add soon.

**Comment by hzoo** [comment]
@KylePDavis ok it's added https://github.com/jscs-dev/babel-jscs
